sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git
      rev-parse --short HEAD; fi)
    - if [ "x$DOCKER_USERNAME" != "x" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
    - docker build -t $DOCKER_REPO/hub .
    - docker tag $DOCKER_REPO/hub $DOCKER_REPO/hub:$TAG
    after_success:
    - if [ "x$DOCKER_USERNAME" != "x" ]; then docker push $DOCKER_REPO/hub && docker push $DOCKER_REPO/hub:$TAG; fi
env:
  global:
  - DOCKER_REPO=eginotebooks
