sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git
      rev-parse --short HEAD; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_REPO/hub .
    - docker tag $DOCKER_REPO/hub $DOCKER_REPO/hub:$TAG
    after_success:
    - docker push $DOCKER_REPO/hub
    - docker push $DOCKER_REPO/hub:$TAG
env:
  global:
  - DOCKER_REPO=eginotebooks
  - secure: p+Vy8vjJzLyuANtdaksYiiCHy53nhIVV4a0bjhZldByeKowjGy3r5RIuoJ5/KgzXMTOiht3gaa/APffYU4jbPDeX7rw0r1QRFOB7lGkgAVYZ0Q9LzNVwqiQZLLYzlqZn7TepAy3SVvlg/CGfR1VNky0sOs0s+iaB6grH//CUqpM2z7ue31D11MIDzJQ0kgqjrszaxWMRifZbtCFZJdbVuSn5vYWIO+0IpTV1e3CeVmp22Y/y9ZKOkZ1WdYsPJocTnQoJQriWUZwOVI6KkW3rMX2SBqfNdvq/WcOsiYydAGlWimlX1MDiZWOwC6Vz83HofQT1yfKMY/rdOJ8iUEZLiPclp/Qe7OKKmb6F2azmTyy2fboFrmj2Y3THk9NWUNn5mfTsrU/Ra2WGKw18pJ1gYjFCPlLb6GHFpnnx481avAzI9vGENo2qN5l1QDJBD0zcyUe0ERllmTwvRaW+dvpSihPjtxALL3OcUjHnYabwlPCPgZi5lyTIj9dNe6j56fvqC7JQEoTfxm1E5FyTsidnBbtNfhcwKXmauthNJgXGljzGxMVvumRQbut6CaobLWejlg4jf5QbjzK39s6vjx+U98oPBrZdOC5lsxNZX6kkkPCDGi2adQc99MIVsbBqfTYIOybX5S3J8m1l/uCKNj8t9eddn2QNU6IIPqE2nVA7rWA=
  - secure: 2e4hOCrFMv5vTsNUs1xw7iHk8ss0kpJlFdwXSuExK5IPYzz501wtcFz1Al3oTV+eUEFCME+VwTJiUmdG21npntYA4QRZmFn7xqi8DmfkM7c92JMR7hMUSWscTbOuiAht1i2ZyIlCelsQ00ztqdPf/YLpU55bMqKj9rqK32hj+B0SkU2YbKcwRdcvcI24ULnAlNKermp/bXukjMAHOK1mH2S4YfgNvnicoTv5xq53rwflNfmY/nCp7qkqKifamMdjitLviOwS+ObgfZfT9WzdPerfnvSYhvzkFVxw/KjyNeLbZ4c40Oh3Hy/hVjKwDbYRC1MRGA6N06by3YdUMawHmA+zgG6zSQyT4IDzdxAOOUxMZb4hl7QsQsksHjQWtVhxj+br6kGU2JGiOKxjX5MhK5iM0VkNQP2PxgFWb0EzNA5cZd1NblMYn/6M71rnWKoqf9UWp5AesDHhYnRP+iv2mm+EVd/2CijuuB7qmDAX6B6PShWjpBMCU43C57D6tpqIakL5UOrLDa538TfQJSwfCb3Wy0kikXW0KwrEeBPqYh0NMd/xL1DIQ+09eE10rw6HHmX4r5Ug45/v/mEOhCFX5BtGzBfZhsZ2LSIZqC+HiN9fMrONo0be6CMxbY/UuTvUpO+1xgshccgC9S9IlX/S0P/Tqhod4hyOgRzPF08UPb8=
