sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git
      rev-parse --short HEAD; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_REPO/hub .
    - docker tag $DOCKER_REPO/hub $DOCKER_REPO/hub:$TAG
    after_success:
    - docker push $DOCKER_REPO/hub
    - docker push $DOCKER_REPO/hub:$TAG
env:
  global:
  - DOCKER_REPO=eginotebooks
  - secure: WPhUvGK20oScJ0bdmYYACDZf8gsD9Odxgq0IFMATeA2OXojGm1De+18x3wJFI/BFUaLsOC01lnJBf99mrEkADwLUgflR/bqQ3bDFBZ6wspJONmMx7iLL3kaHvuFJr/GhcYQHnSU1psEvrtvduUCWis3SB7Rub0dwW0z4xMWrjLiQ7q3HENptHNK3GjSpvTR+mjQWb78iFtxdXWqwA7UXr/g0SNqKl1/E1ndSlSQuhRWllD4wHQs7RBUfpqy2WOzQ+gTFMF+y+n8zXWBZ1YFf1kEpxhShKoSS7Da71FGCfWwJKF/LgzmzH1L/qXZdysEtdJVAn+mOyyYm2kYlIKLUufd8exrTeItVBCBgbzmuweV2b2DSPVGcOpPpbTkuwLHALaC3+PDLoEgbVfborQLFDTONcagsN6BJ8WS7mT0jP+hi3+zGquMl4FOHvOi76ixEeL0xfsMAcb/jjwxUnjciLThfWuYXbXK8TRjhUqDE4xrUJX6wp+3ixcnW/ARXLi0Meji0q78cjnA4AEVbI38vThwsu4OwYY/+ieKIl9jDDGsuR1X+DwNgoDxs2pVS1VoFhLvA8QnNAR9riPpeNpLRizmMzCnmFQcXsglSnS+FlLO51XPW4BlsQrbB9P7fCokWJR2ja8FIcujEcSl+nIOti/D3FtsXGUcu6aw87IoXzmE=
  - secure: vG2OB1O4diEOzxrHdq/sz//kczM/wzBxb+YUXlLA8oEPdiQj5KgKLXr3sc7ZWFxWgHPVfxqtQWPb1VB6WFXpDkBHBDF0B0by6hPgKoDdaWUc0yMUip/R5oxtHcxeQ2ckUtgnH/rLnO+LQS9a+/n2jWYp/D9HnEehpzRIlNFcBB7MwF0of7NZmz35PEFSGJyMZtquowmNQgDktgCP/2iV5GY4alxdWvZ5ypuzHq14Z6J4g4ZzuqzwoLF+XiSL0YRi65/HZX6LT8JdCvjQatz3dpQFvYNdqfG644ploqP/Z2GH/++GSGB0x2M7x9khanZnXaUSTdjXhULj7YdYqwdI9HVg+vCo8L/xFtmwVHioKsexU2BcqlOXOfQxiqYn+whMwOGTr7vU44qirYU/0Rm5YW73BbbudGx8xCtwH3Np0HMaX8GhKIU4S7Oko8+o76dGMy9rQ+7VbAgdNFwqRfMBEkSgrPf06I/u2Wvx5HNeACNIBClU/HiYT9ZI9as/mVoECUTZtmw2BKwzaarIvbJuwpeLszxzzhUynADe79fxdLi7PsZQf1gGhb//fQDconRA/mvK7b0H3BrDK8jJaOi/a/vuxKaZTTBSeHIFc74OZN30d22ZJYX+97RJVhwySGQlG8Z67l+cJccWrOGPZcAjinJezF+C75pNQ9iIsXGrvJI=
