---
name: Lint

on: [pull_request, push]

jobs:
  super-lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter on new changes
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only check new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Fail on errors
          DISABLE_ERRORS: false
          # JSCPD is failing in the symlink, so avoiding it
          VALIDATE_JSCPD: false
